yahoonews <- WebCorpus(YahooNewsSource("Switzerland"))
yahoonews1<- WebCorpus(YahooNewsSource("Liechtenstein"))
yahoonews2<- WebCorpus(YahooNewsSource("Swiss Fran"))
yahoonews2<- WebCorpus(YahooNewsSource("Swiss Franc"))
# ?WebCorpus(YahooNewsSource("Swiss Franc"))
yahoonewsjap<- WebCorpus(YahooNewsSource("Japanese"))
yahoonewsjap1<- WebCorpus(YahooNewsSource("JPY"))
> class(yahoonews)
 lapply(inspect(yahoonews), write, "swtz.txt", append=TRUE, ncolumns=1000)
